# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
        max-http-header-size: 3145728
    port: 8081
    context-path: /

spring : 
    dubbo : 
        application :   
            name : consumer
        registry :  
            address : zookeeper://192.168.73.134:2181  
        scan: com.cn.system.api.service
        
    #解决tomcat同时部署两个SpringBoot应用提示InstanceAlreadyExistsException
    jmx:
        default-domain: app
    # 环境 dev|test|prod
    profiles:
        active: dev
    freemarker:
      request-context-attribute: request
      
#    devtools:
#      restart:
#        enabled: true
#        exclude: WEB-INF/**

#logging
logging:
   config: classpath:logback-spring.xml
